print("====================================================")                      
print("              Welcome to Indian AI production       ")
print("====================================================")
print("                  About Me                          ")
print("              Name: Akanksha Burle                  ")
print("              Age: 16                               ")
print("              City: Sindi(rly)                      ")
print("                    Country: India                  ")
print("               Email : akankshaburle32@gmail.com    ")
print("               Phone no. 9284076091                 ")